# Generated by Django 5.1.2 on 2024-10-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('nicknames', models.CharField(blank=True, max_length=200)),
                ('emoji_preference', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('tail', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('magical_properties', models.TextField(blank=True)),
                ('image', models.ImageField(default='default_cat.png', upload_to='cat_images/')),
            ],
        ),
    ]
